### ISSUE TITLE
Issue during inference using POTO

### ISSUE THREAD

**Issue by SunSet0864** [Megvii-BaseDetection/DeFCN#11]
NMS post-processing is not used in POTO. The code:
https://github.com/Megvii-BaseDetection/DeFCN/blob/a82393e290455fd11a1a088723a8050791b44c15/playground/detection/coco/poto.res50.fpn.coco.800size.3x_ms.3dmf/fcos.py#L407
says that topk_candidates and score_threshold are useless in POTO. So how to modify the codes in function "inference_single_image" when using POTO? Would you like to give some ideas? Thank you.

**Comment by wjfwzzc** [comment]
Just remove them and keep the sort only.
