### ISSUE TITLE
there is a wrong when run this code with the order pods_train --num-gpus 2

### ISSUE THREAD

**Issue by KenRamzes** [Megvii-BaseDetection/DeFCN#13]
![截屏2021-07-28 下午6 36 58](https://user-images.githubusercontent.com/34309243/127308707-ee070a3e-4bbf-4c38-a02d-a90a17883c65.png)
how to train deFCN with 2 gpu？

**Comment by wjfwzzc** [comment]
I never tested `cvpods` in conda env.
If you have any issue about `cvpods`, please submit to [cvpods](https://github.com/Megvii-BaseDetection/cvpods/issues). Here is only for the issues about the implementation.
