### ISSUE TITLE
关于CrowdHuman数据集

### ISSUE THREAD

**Issue by Asthestarsfalll** [Megvii-BaseDetection/DeFCN#17]
您好！
由于cvpods封装程度较高，有些地方没有理解。
请问DeFCN训练时使用的是CrowdHuman中的Visible box还是Full box？
配置文件中num_classes=1，那么类别中的mask是被去除还是转化为person呢？
box的格式是表示xmin,ymin,xmax,ymax两个点的坐标还是中心点坐标与长宽呢？

**Comment by wjfwzzc** [comment]
1. Full box.
2. 不明白“类别中的mask”是什么意思。在DeFCN中，1类与80类在各个地方的处理上都没有区别。
3. xyxy，左上角与右下角。

**Comment by Asthestarsfalll** [comment]
> 1. Full box.
> 2. 不明白“类别中的mask”是什么意思。在DeFCN中，1类与80类在各个地方的处理上都没有区别。
> 3. xyxy，左上角与右下角。

CrowdHuman的odgt文件中有两个类别：person、mask。
查阅相关资料发现：“mask是指這類的情況：crowd, reflection, something like person … 因此，一般我們只需要取出person即可”。
然而检查megstudio中CrowdHuman数据集提供的annotations_train.json，其中annotations的数量应该是person+mask，也就是我的疑问“类别中的mask是被去除还是转化为person”。

**Comment by wjfwzzc** [comment]
代码层面上，`cvpods`会根据`ignore`来确定是否去除该annotation，没有考虑`tag`是否是`"mask"`：
https://github.com/Megvii-BaseDetection/cvpods/blob/53fd3df74dc0bda9c0718f43a293bfb1bcd34fb6/cvpods/data/datasets/crowdhuman.py#L183
https://github.com/Megvii-BaseDetection/DeFCN/blob/a82393e290455fd11a1a088723a8050791b44c15/playground/detection/crowdhuman/poto.res50.fpn.crowdhuman.800size.30k.3dmf.aux/fcos.py#L139-L140
不过，应该所有`tag="mask"`都被ignore了，根据 <https://www.crowdhuman.org/download.html>

**Comment by Asthestarsfalll** [comment]
了解了，感谢！
