### ISSUE TITLE
-bash: pods_train: command not found

### ISSUE THREAD

**Issue by dulibubai** [Megvii-BaseDetection/DeFCN#18]
I have done Get Started successfully, but it happened -bash: pods_train: command not found

**Comment by wjfwzzc** [comment]
Seem that the installation of `cvpods` is not successful. You may need to check your enviroments such as `~/.local/bin` in `PATH`. Please refer to `https://github.com/Megvii-BaseDetection/cvpods` for more information.

**Comment by wjfwzzc** [comment]
Long times without further response. Close it.
