### ISSUE TITLE
ImportError: cannot import name 'config' from 'config'

### ISSUE THREAD

**Issue by daniel-qian** [Megvii-BaseDetection/DeFCN#19]
Hi, when i try to run the command 'pods_test' or 'pods_train', i got the error as follow:

Traceback (most recent call last):
  File "xxx/cvpods/tools/test_net.py", line 192, in <module>
    from config import config  # isort:skip  # noqa: E402

Any suggestion to fix this?
many thanks

**Comment by FateScript** [comment]
Did you enter the running dir which contains a config.py? @daniel-qian

**Comment by daniel-qian** [comment]
Hi, thanks for replying.

I did, but it didnt work
> Did you enter the running dir which contains a config.py? @daniel-qian

But i got it working by changing the name of the config.py into some other name, such as config_xxx. (Because i thought this may caused by overlapping imports name with the envrionment configuration.)

Now i am facing another issue which is when i try to run test_net.py with the pre-trained model, i got the error

File "/disk2t/qrl/e2efcn/cvpods/tools/test_net.py", line 136, in get_valid_files
    remote_file_path = os.path.join(cfg.OSS.DUMP_PREFIX, model_prefix)
AttributionError: 'CustomFCOSConfig' object has no attribute 'OSS'

I have read the sources code for a while, i supposed the attribute 'OSS' is used to extract the path to the remote file, any idea where i went wrong?

**Comment by FateScript** [comment]
Well, it's a bug. I will fix it later.

For you, using a local file to test is ok. Just download the model weights and run:
```bash
pods_test --num-gpus 8  MODEL.WEIGHTS /path/to/your/downloaded/ckpt.pth
```

**Comment by daniel-qian** [comment]
thank you for answering.  I will have a go on this.

I was considering using a local model, but in the helps documents of pods_test, there is no such argument MODEL.WEIGHTS, it will be nice to have this in the helps docs.
