### ISSUE TITLE
Dose it support limited GPU index?

### ISSUE THREAD

**Issue by rainylt** [Megvii-BaseDetection/DeFCN#2]
There are only 2 gpus free in my machine now, so I tried to limit the gpu index and numbers as follow, and it raised such error:
(open-mmlab) liangtian@node001:~/project/DeFCN/playground/detection/coco/poto.res50.fpn.coco.800size.3x_ms.3dmf$ CUDA_VISIBLE_DEVICES=4,5 pods_train --num-gpus 2
Traceback (most recent call last):
  File "/mnt/xfs1/home/liangtian/project/cvpods/tools/train_net.py", line 27, in <module>
    from cvpods.checkpoint import DetectionCheckpointer
  File "/mnt/xfs1/home/liangtian/project/cvpods/cvpods/__init__.py", line 3, in <module>
    from .utils import setup_environment
  File "/mnt/xfs1/home/liangtian/project/cvpods/cvpods/utils/__init__.py", line 27, in <module>
    from .visualizer import ColorMode, VideoVisualizer, VisImage, Visualizer, colormap, random_color
  File "/mnt/xfs1/home/liangtian/project/cvpods/cvpods/utils/visualizer/__init__.py", line 5, in <module>
    from .video_visualizer import *
  File "/mnt/xfs1/home/liangtian/project/cvpods/cvpods/utils/visualizer/video_visualizer.py", line 6, in <module>
    from .visualizer import ColorMode, Visualizer, _create_text_labels, _PanopticPrediction
  File "/mnt/xfs1/home/liangtian/project/cvpods/cvpods/utils/visualizer/visualizer.py", line 17, in <module>
    from cvpods.structures import BitMasks, Boxes, BoxMode, Keypoints, PolygonMasks, RotatedBoxes
  File "/mnt/xfs1/home/liangtian/project/cvpods/cvpods/structures/__init__.py", line 2, in <module>
    from .boxes import Boxes, BoxMode, pairwise_ioa, pairwise_iou
  File "/mnt/xfs1/home/liangtian/project/cvpods/cvpods/structures/boxes.py", line 11, in <module>
    from cvpods.layers import cat
  File "/mnt/xfs1/home/liangtian/project/cvpods/cvpods/layers/__init__.py", line 4, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/mnt/xfs1/home/liangtian/project/cvpods/cvpods/layers/deform_conv.py", line 11, in <module>
    from cvpods import _C
ImportError: /mnt/xfs1/home/liangtian/project/cvpods/cvpods/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6cvpods26psroi_pooling_forward_cudaERN2at6TensorES2_S2_iifii

**Comment by wjfwzzc** [comment]
`cvpods` supports limited GPU index.
It seems a building error. Please try rebuilding `cvpods`.

**Comment by rainylt** [comment]
> `cvpods` supports limited GPU index.
> It seems a building error. Please try rebuilding `cvpods`.

I'm so upset that I can't tackle it in my environment. I have created a new conda env for cvpods with libraries needed. And I have rebuilt cvpods twice without error, but the error above is still there. 
I have found a closed issue saying cvpods can't build in conda env, is it true? Anyway, it will be so nice that if you can commit a dockerfile to avoid environment inconsistency. Just a suggestion.

**Comment by poodarchu** [comment]
can you share your compiling log;
did you clean the cache before recompile cvpods?

**Comment by wjfwzzc** [comment]
I never tested `cvpods` in conda env.
As far as I know, `cvpods` will support docker in recent days.
If you have any issue about `cvpods`, please submit to [cvpods](https://github.com/Megvii-BaseDetection/cvpods/issues). Here is only for the issues about the implementation.

**Comment by ranjiewwen** [comment]
> > `cvpods` supports limited GPU index.
> > It seems a building error. Please try rebuilding `cvpods`.
> 
> I'm so upset that I can't tackle it in my environment. I have created a new conda env for cvpods with libraries needed. And I have rebuilt cvpods twice without error, but the error above is still there.
> I have found a closed issue saying cvpods can't build in conda env, is it true? Anyway, it will be so nice that if you can commit a dockerfile to avoid environment inconsistency. Just a suggestion.

i meet the same problem, build sucess  and run error . 
`ImportError: /data/youcaizi/detection/cvpods/cvpods/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6cvpods26psroi_pooling_forward_cudaERN2at6TensorES2_S2_iifii`

**Comment by wjfwzzc** [comment]
> > > `cvpods` supports limited GPU index.
> > > It seems a building error. Please try rebuilding `cvpods`.
> > 
> > 
> > I'm so upset that I can't tackle it in my environment. I have created a new conda env for cvpods with libraries needed. And I have rebuilt cvpods twice without error, but the error above is still there.
> > I have found a closed issue saying cvpods can't build in conda env, is it true? Anyway, it will be so nice that if you can commit a dockerfile to avoid environment inconsistency. Just a suggestion.
> 
> i meet the same problem, build sucess and run error .
> `ImportError: /data/youcaizi/detection/cvpods/cvpods/_C.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN6cvpods26psroi_pooling_forward_cudaERN2at6TensorES2_S2_iifii`

It seems that `cvpods` does not support conda well. @poodarchu Could you provide commits to support `docker`?
