### ISSUE TITLE
mAP is the same after more than 500.000 steps

### ISSUE THREAD

**Issue by attilab97** [Megvii-BaseDetection/DeFCN#20]
Hi there,

I am facing a strange situation. I did an inference at step no. 1.000.000 out of 2.000.000 on trained with the same config as poto.res50.fpn.coco.800size.3x_ms.3dmf_wo_gn.aux. The problem is that I cannot see any difference in inference results when I do it again at step 1.500.000. The results of the inference are the same.

Do you know why this might happen?

Thank you.

**Comment by wjfwzzc** [comment]
Sorry I don't know what happened, sound like there are some bugs in your modification.
