### ISSUE TITLE
How the set the regression target for the  ground truth bbox?

### ISSUE THREAD

**Issue by Hwang64** [Megvii-BaseDetection/DeFCN#3]
If the gt_bbox is to small, no shift_point in each fpn_level is in the range of spatial prior, so no correponding regression target for this gt_bbox. How to set the regression target in this situation?
Looking forward to your reply, thank you!

**Comment by wjfwzzc** [comment]
These ground-truths will be missed, however such ground-truths are rare in common datasets like COCO.
If you want to handle these ground-truths, you may modify the default spatial prior, such as expanding the radius or changing it to a soft version.
