### ISSUE TITLE
Does the weight file provided are trained on pytorch=1.6.0 or higher version?

### ISSUE THREAD

**Issue by hedes1992** [Megvii-BaseDetection/DeFCN#5]
Hello,
    Thanks for your excellent work.
    I just install the cvpods with (pytorch=1.4.0, cudatoolkit=10.1, torchvision=0.5.0), and can run pods_train with the POTO's config.py.
    But when I download the weight file "poto.res50.fpn.coco.800size.3x_ms.3dmf.aux.cf438670.pth" and run pods_test, it raise the error like the following: 

> RuntimeError: version_ <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /opt/conda/conda-bld/pytorch_1579022034529/work/caffe2/serialize/inline_container.cc:132, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 2. Your PyTorch installation may be too old. (init at /opt/conda/conda-bld/pytorch_1579022034529/work/caffe2/seri
alize/inline_container.cc:132)

I google this and find that maybe the pytorch version should be larger than 1.6.0, like this [issue](https://github.com/pytorch/vision/issues/1943)

**Comment by wjfwzzc** [comment]
Yes, `cvpods` supports pytorch >= 1.3, but experiments here are conducted on pytorch >= 1.7. You can refer to enviroment details in the provided training logs. We'll update README.md soon.
