### ISSUE TITLE
Confusions about the paper

### ISSUE THREAD

**Issue by SunSet0864** [Megvii-BaseDetection/DeFCN#6]
Aux_loss is contradict to the core insight of the paper. Concretely, the insight of the paper is to design an one-to-one label asssignment method, however, aux_loss is an one-to-many assignment method. So the proposed method can also be realized by using ATSS with an proper one-to-one label assignment (e.g., POTO in this paper). No correponding results varify which loss is more import to the performance.

**Comment by wjfwzzc** [comment]
Table 1 in the paper tells us **one-to-one label assignment is crucial for NMS-free**. However one-to-one assignment faces performance decreasing, to alleviate it we introduce one-to-many assignment with stronger supervision.
Without one-to-one assignment, NMS cannot be removed. Obviously, the one-to-one assignment is the most important part for the performance *in E2E scenarios*. Auxiliary loss with one-to-many assignment is an incremental technique.

**Comment by wjfwzzc** [comment]
Two weeks without response. Close it.
