### ISSUE TITLE
Assertion issue

### ISSUE THREAD

**Issue by Hwang64** [Megvii-BaseDetection/DeFCN#9]
In the function apply_deltas(/cvpods/modeling/box_regression.py), there is a assertion at the first of this function. I think there may be some considerations for this assertion, and maybe sometimes, the deltas will be infinite. So could you share some experiences when debuging the code here?

**Comment by wjfwzzc** [comment]
There is no specific consideration, just assertions for debugging (such as broken data processing procedures or wrong annotations for new datasets). However, I'm not sure when the deltas should be infinite if there is nothing wrong. If it confused you, or you met some situations where the infinite deltas are neccesary, you can remove these assertions by yourselves.
